//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Possession = new HashSet<Possession>();
        }
    
        public int IdCar { get; set; }
        public string RegNumber { get; set; }
        public Nullable<int> IdModel { get; set; }
        public Nullable<int> IdCollor { get; set; }
        public Nullable<double> Power { get; set; }
        public Nullable<bool> Imege { get; set; }
        public Nullable<bool> Show { get; set; }
    
        public virtual Collor Collor { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Possession> Possession { get; set; }
    }
}
