//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalties
    {
        public int IdPenalties { get; set; }
        public Nullable<int> IdViolations { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> DataPenalties { get; set; }
        public Nullable<double> Prece { get; set; }
    
        public virtual TypeViolations TypeViolations { get; set; }
        public virtual Violations Violations { get; set; }
    }
}
