//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Possession()
        {
            this.Violations = new HashSet<Violations>();
        }
    
        public int IdPossession { get; set; }
        public int IdDrivers { get; set; }
        public int IdCar { get; set; }
        public Nullable<System.DateTime> DataBuy { get; set; }
        public Nullable<System.DateTime> DataSale { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Drivers Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Violations> Violations { get; set; }
    }
}
