//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Patronumic { get; set; }
        public Nullable<int> IdActor { get; set; }
        public byte[] Pthoto { get; set; }
        public Nullable<bool> Show { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Login Login { get; set; }
    }
}
