//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Violations()
        {
            this.Penalties = new HashSet<Penalties>();
        }
    
        public int IdViolations { get; set; }
        public Nullable<int> IdPossession { get; set; }
        public Nullable<System.DateTime> Data1 { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdTypeViolations { get; set; }
    
        public virtual Possession Possession { get; set; }
        public virtual TypeViolations TypeViolations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalties> Penalties { get; set; }
    }
}
